// Code generation: turns the project contract into a real-looking Next.js (App Router)
// source tree. Deterministic, so diffs between checkpoints are meaningful.
import { agentCode, pascal, kebab, snake } from './frameworks.js';
import { tableById, agentById } from './schema.js';

const EXT_LANG = { ts: 'ts', tsx: 'tsx', js: 'js', mjs: 'js', json: 'json', md: 'md', sql: 'sql', yaml: 'yaml', yml: 'yaml', py: 'py', toml: 'toml', css: 'css', txt: 'text', example: 'sh', env: 'sh' };
export function langOf(path = '') {
  const base = path.split('/').pop();
  if (base.startsWith('.env')) return 'sh';
  return EXT_LANG[base.split('.').pop()] || 'text';
}

/** app/<route>/page.tsx for a screen route ('/' → app/page.tsx, '/leads/:id' → app/leads/[id]/page.tsx). */
export function pageFile(route = '/') {
  const parts = String(route).split('/').filter(Boolean).map((s) => (s.startsWith(':') ? `[${s.slice(1)}]` : s));
  return ['app', ...parts, 'page.tsx'].join('/');
}
const INLINE = new Set(['header', 'hero', 'text']);
function blockFile(screen, block) {
  if (block.file) return block.file;
  if (INLINE.has(block.type)) return pageFile(screen.route);
  return `components/${pascal(block.title || `${screen.title} ${block.type}`) || 'Block'}.tsx`;
}

/** The file that renders a given block (for X-ray "open code"). */
export function fileForBlock(project, blockId) {
  for (const s of project?.screens || []) for (const b of s.blocks || []) if (b.id === blockId) return blockFile(s, b);
  return null;
}

const q = (s) => JSON.stringify(s ?? '');
const compName = (file) => file.split('/').pop().replace(/\.tsx?$/, '');

// ---------------------------------------------------------------------------
// Component bodies per block type
// ---------------------------------------------------------------------------
function componentCode(project, block, file) {
  const name = compName(file);
  const t = block.bind?.table ? tableById(project, block.bind.table) : null;
  const a = block.bind?.agent ? agentById(project, block.bind.agent) : null;
  const p = block.props || {};
  const head = [`// ${block.title || block.type} — generated by Architect from block ${block.id}${block.promise ? ` (promise ${block.promise})` : ''}`];
  const imports = [];
  let body;
  if (t) imports.push(`import { listRows } from '@/lib/db';`);
  if (a) imports.push(`import { runAgent } from '@/lib/agents';`);
  const tn = t ? snake(t.id) : 'items';
  switch (block.type) {
    case 'table': {
      const cols = (p.columns?.length ? p.columns : (t?.columns || []).map((c) => c.key)).slice(0, 8);
      const labels = cols.map((k) => t?.columns.find((c) => c.key === k)?.label || k);
      body = `export default async function ${name}() {
  const rows = await listRows(${q(tn)}, { limit: ${p.pageSize || 25} });
  return (
    <section className="card">
      <h2>${block.title || t?.name || 'Records'}</h2>
      <table>
        <thead><tr>${labels.map((l) => `<th>${l}</th>`).join('')}</tr></thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.id}>${cols.map((k) => `<td>{String(r.${k} ?? '')}</td>`).join('')}</tr>
          ))}
        </tbody>
      </table>
    </section>
  );
}`;
      break;
    }
    case 'kpis':
      body = `const items = ${JSON.stringify((p.items || []).map((i) => ({ label: i.label, value: i.value, delta: i.delta })), null, 2)};

export default function ${name}() {
  return (
    <div className="kpis">
      {items.map((k) => (
        <div key={k.label} className="kpi"><span>{k.label}</span><strong>{k.value}</strong><em>{k.delta}</em></div>
      ))}
    </div>
  );
}`;
      break;
    case 'chart':
      imports.push(`import { Chart } from '@/components/ui/Chart';`);
      body = t ? `export default async function ${name}() {
  const rows = await listRows(${q(tn)});
  const counts = new Map<string, number>();
  for (const r of rows) counts.set(r.${p.groupBy || 'status'}, (counts.get(r.${p.groupBy || 'status'}) ?? 0) + 1);
  return <Chart kind=${q(p.kind || 'bar')} title=${q(block.title || '')} data={[...counts].map(([label, value]) => ({ label, value }))} />;
}` : `const data = ${JSON.stringify(p.series || [])};
export default function ${name}() {
  return <Chart kind=${q(p.kind || 'bar')} title=${q(block.title || '')} data={data} />;
}`;
      break;
    case 'form':
      if (t) imports.push(`import { insertRow } from '@/lib/db';`, `import { revalidatePath } from 'next/cache';`);
      body = `export default function ${name}() {
  async function submit(form: FormData) {
    'use server';
${t ? `    await insertRow(${q(tn)}, Object.fromEntries(form));\n    revalidatePath('/');` : '    console.log(Object.fromEntries(form));'}
  }
  return (
    <form action={submit} className="card">
${(p.fields || []).map((f) => `      <label>${f.label}<input name=${q(f.key)} type=${q(f.type === 'number' ? 'number' : f.type === 'email' ? 'email' : 'text')} /></label>`).join('\n')}
      <button type="submit">${p.submitLabel || 'Submit'}</button>
    </form>
  );
}`;
      break;
    case 'agentChat':
      head.unshift(`'use client';`);
      imports.length = 0;
      imports.push(`import { useState } from 'react';`);
      body = `export default function ${name}() {
  const [messages, setMessages] = useState([{ role: 'assistant', text: ${q(p.greeting || `Hi, I'm ${a?.name || 'your assistant'}.`)} }]);
  const [input, setInput] = useState('');
  async function send() {
    const text = input.trim();
    if (!text) return;
    setMessages((m) => [...m, { role: 'user', text }]);
    setInput('');
    const res = await fetch('/api/agents/${a ? kebab(a.id) : 'assistant'}', { method: 'POST', body: JSON.stringify({ input: text }) });
    const out = await res.json();
    setMessages((m) => [...m, { role: 'assistant', text: out.reply }]);
  }
  return (
    <section className="card chat">
      {messages.map((m, i) => <p key={i} className={m.role}>{m.text}</p>)}
      <input value={input} onChange={(e) => setInput(e.target.value)} placeholder=${q(p.placeholder || 'Ask anything…')} />
      <button onClick={send}>Send</button>
    </section>
  );
}`;
      break;
    case 'agentActivity':
      imports.length = 0;
      imports.push(`import { recentRuns } from '@/lib/agents';`);
      body = `export default async function ${name}() {
  const runs = await recentRuns(${q(a?.id || '')}, ${p.limit || 5});
  return (
    <ul className="card activity">
      {runs.map((r) => <li key={r.id}><strong>{r.summary}</strong><span>{r.steps} steps · {r.at}</span></li>)}
    </ul>
  );
}`;
      break;
    default: {
      const title = p.titleKey || t?.columns[0]?.key || 'title';
      const sub = p.subtitleKey || p.metaKey || t?.columns[1]?.key || 'id';
      body = t ? `export default async function ${name}() {
  const rows = await listRows(${q(tn)});${block.type === 'kanban' ? `
  const lanes = ${JSON.stringify(t.columns.find((c) => c.key === p.groupBy)?.options || [])};
  return (
    <div className="kanban">
      {lanes.map((lane) => (
        <div key={lane} className="lane"><h3>{lane}</h3>
          {rows.filter((r) => r.${p.groupBy || 'status'} === lane).map((r) => <article key={r.id}><strong>{r.${title}}</strong><span>{r.${sub}}</span></article>)}
        </div>
      ))}
    </div>
  );` : `
  return (
    <div className="${block.type}">
      {rows.map((r) => <article key={r.id}><strong>{r.${title}}</strong><span>{r.${sub}}</span></article>)}
    </div>
  );`}
}` : `export default function ${name}() {
  return <section className="card">${block.title || ''}</section>;
}`;
    }
  }
  return `${head.join('\n')}\n${imports.join('\n')}${imports.length ? '\n\n' : '\n'}${body}\n`;
}

function pageCode(project, screen) {
  const comps = [];
  const parts = [];
  for (const b of screen.blocks || []) {
    const f = blockFile(screen, b);
    if (f.startsWith('components/')) {
      const n = compName(f);
      if (!comps.includes(n)) comps.push(n);
      parts.push(`      <${n} />`);
    } else if (b.type === 'header' || b.type === 'hero') {
      const p = b.props || {};
      parts.push(`      <header className="page-header">\n        <h1>${p.title || screen.title}</h1>\n${p.subtitle ? `        <p>${p.subtitle}</p>\n` : ''}${(p.actions || []).map((x) => `        <button className=${q(x.variant || 'secondary')}>${x.label}</button>\n`).join('')}      </header>`);
    } else if (b.type === 'text') parts.push(`      <p className="prose">${String(b.props?.body || '').replace(/\*\*/g, '').replace(/\n/g, ' ')}</p>`);
  }
  return `// ${screen.title} (${screen.route}) — generated by Architect
${comps.map((n) => `import ${n} from '@/components/${n}';`).join('\n')}

export const metadata = { title: ${q(`${screen.title} · ${project.name}`)} };

export default function ${pascal(screen.title) || 'Page'}Page() {
  return (
    <main className="grid">
${parts.join('\n')}
    </main>
  );
}
`;
}

const SQL_TYPE = { number: 'numeric', money: 'numeric(12,2)', percent: 'numeric(5,2)', score: 'integer', date: 'date', datetime: 'timestamptz', bool: 'boolean', tags: 'text[]' };
const sqlVal = (v) => (v == null ? 'NULL' : typeof v === 'number' || typeof v === 'boolean' ? String(v) : Array.isArray(v) ? `ARRAY[${v.map(sqlVal).join(', ')}]` : `'${String(v).replace(/'/g, "''")}'`);

function schemaSql(project) {
  const out = ['-- Database schema — generated by Architect', '-- Apply with: npm run db:migrate', ''];
  for (const t of project.data?.tables || []) {
    const cols = [`  id text PRIMARY KEY`];
    for (const c of t.columns || []) if (c.key !== 'id') cols.push(`  ${snake(c.key)} ${SQL_TYPE[c.type] || 'text'}${c.type === 'status' && c.options?.length ? ` CHECK (${snake(c.key)} IN (${c.options.map(sqlVal).join(', ')}))` : ''}`);
    cols.push(`  created_at timestamptz NOT NULL DEFAULT now()`);
    out.push(`-- ${t.name}${t.rules ? ` · access: ${t.rules}` : ''}${t.connection ? ` · synced from ${t.connection}` : ''}`, `CREATE TABLE IF NOT EXISTS ${snake(t.id)} (`, cols.join(',\n'), ');', '');
  }
  return out.join('\n');
}
function seedSql(project) {
  const out = ['-- Sample data (clearly marked as sample in the app until a live source is connected)', ''];
  for (const t of project.data?.tables || []) {
    const keys = ['id', ...(t.columns || []).map((c) => c.key).filter((k) => k !== 'id')];
    const rows = (t.rows || []).slice(0, 40);
    if (!rows.length) continue;
    out.push(`INSERT INTO ${snake(t.id)} (${keys.map(snake).join(', ')}) VALUES`);
    out.push(rows.map((r) => `  (${keys.map((k) => sqlVal(r[k])).join(', ')})`).join(',\n') + '\nON CONFLICT (id) DO NOTHING;', '');
  }
  return out.join('\n');
}

function testsSpec(project) {
  const ps = (project.plan?.promises || []).filter((p) => p.status !== 'deferred');
  const firstRoute = project.screens?.[0]?.route || '/';
  return `// Every promise in the plan becomes a Playwright test. Run with: npm test
import { test, expect } from '@playwright/test';

${ps.map((p) => `test.describe(${q(`${p.id}: ${p.title}`)}, () => {
${(p.checks || []).map((c) => `  test(${q(c)}, async ({ page }) => {
    await page.goto(${q(firstRoute)});
    await expect(page.locator('main')).toBeVisible();
  });`).join('\n\n')}
});`).join('\n\n')}
`;
}

/**
 * The project's source tree as it would be exported to GitHub.
 * @returns {{path:string, lang:string, content:string, generated:string, edited:boolean}[]}
 */
export function generateFiles(project) {
  if (!project) return [];
  const files = [];
  const add = (path, content) => { if (!files.some((f) => f.path === path)) files.push({ path, content }); };
  const screens = project.screens || [];
  const tables = project.data?.tables || [];
  const agents = project.agents || [];
  const slug = project.slug || kebab(project.name || 'app');

  add('package.json', JSON.stringify({
    name: slug, version: '0.1.0', private: true,
    scripts: { dev: 'next dev', build: 'next build', start: 'next start', test: 'playwright test', 'db:migrate': 'psql "$DATABASE_URL" -f db/schema.sql', 'db:seed': 'psql "$DATABASE_URL" -f db/seed.sql' },
    dependencies: { next: '14.2.5', react: '18.3.1', 'react-dom': '18.3.1', pg: '8.12.0', zod: '3.23.8', yaml: '2.5.0' },
    devDependencies: { typescript: '5.5.4', '@types/react': '18.3.3', '@types/pg': '8.11.6', '@playwright/test': '1.46.0' },
  }, null, 2) + '\n');
  add('app/layout.tsx', `// Root layout — navigation for ${project.name}
import './globals.css';
import Link from 'next/link';

export const metadata = { title: ${q(project.name)}, description: ${q(project.description || project.plan?.summary || '')} };

const nav = ${JSON.stringify(screens.filter((s) => s.nav !== false && !s.route.includes(':')).map((s) => ({ href: s.route, label: s.title })), null, 2)};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <aside className="sidebar">
          <strong>${project.name}</strong>
          {nav.map((n) => <Link key={n.href} href={n.href}>{n.label}</Link>)}
        </aside>
        <div className="content">{children}</div>
      </body>
    </html>
  );
}
`);
  const th = project.theme || {};
  add('app/globals.css', `/* Theme: ${th.preset || 'custom'} */\n:root {\n  --primary: ${th.primary || '#2F5BEA'};\n  --accent: ${th.accent || '#7446F0'};\n  --radius: ${th.radius ?? 10}px;\n  --font: '${th.font || 'Inter'}', system-ui, sans-serif;\n}\nbody { margin: 0; display: flex; font-family: var(--font); }\n.sidebar { width: 220px; padding: 16px; display: flex; flex-direction: column; gap: 8px; }\n.content { flex: 1; padding: 24px; }\n.grid { display: grid; grid-template-columns: repeat(12, 1fr); gap: 16px; }\n.card { border: 1px solid #e5e7eb; border-radius: var(--radius); padding: 16px; }\n`);
  for (const s of screens) add(pageFile(s.route), pageCode(project, s));
  const home = screens.find((s) => s.nav !== false && !String(s.route).includes(':'));
  if (home) add('app/page.tsx', `// Home route — sends visitors to the first screen of ${project.name}.\nimport { redirect } from 'next/navigation';\n\nexport default function Home() {\n  redirect(${q(home.route)});\n}\n`);
  for (const s of screens) for (const b of s.blocks || []) {
    const f = blockFile(s, b);
    if (f.startsWith('components/')) add(f, componentCode(project, b, f));
  }
  if (screens.some((s) => s.blocks?.some((b) => b.type === 'chart'))) {
    add('components/ui/Chart.tsx', `'use client';\n// Minimal chart primitive used by generated chart blocks.\ntype Point = { label: string; value: number };\nexport function Chart({ kind, title, data }: { kind: string; title: string; data: Point[] }) {\n  const max = Math.max(1, ...data.map((d) => d.value));\n  return (\n    <figure className={\`card chart chart--\${kind}\`}>\n      <figcaption>{title}</figcaption>\n      {data.map((d) => <div key={d.label} style={{ width: \`\${(d.value / max) * 100}%\` }}>{d.label} · {d.value}</div>)}\n    </figure>\n  );\n}\n`);
  }
  add('lib/db.ts', `// Postgres access — tables: ${tables.map((t) => snake(t.id)).join(', ') || 'none'}
import { Pool } from 'pg';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const TABLES = new Set(${JSON.stringify(tables.map((t) => snake(t.id)))});

export async function listRows(table: string, { limit = 100 } = {}) {
  if (!TABLES.has(table)) throw new Error(\`Unknown table \${table}\`);
  const { rows } = await pool.query(\`SELECT * FROM \${table} ORDER BY created_at DESC LIMIT $1\`, [limit]);
  return rows;
}

export async function insertRow(table: string, values: Record<string, unknown>) {
  if (!TABLES.has(table)) throw new Error(\`Unknown table \${table}\`);
  const keys = Object.keys(values);
  const sql = \`INSERT INTO \${table} (id, \${keys.join(', ')}) VALUES (gen_random_uuid()::text, \${keys.map((_, i) => '$' + (i + 1)).join(', ')}) RETURNING *\`;
  const { rows } = await pool.query(sql, Object.values(values));
  return rows[0];
}
`);
  add('lib/agents.ts', `// Server-side agent runner. Agent definitions live in /agents/*/agent.yaml
import { readFile } from 'node:fs/promises';
import YAML from 'yaml';

export async function loadAgent(id: string) {
  return YAML.parse(await readFile(\`agents/\${id}/agent.yaml\`, 'utf8'));
}

export async function runAgent(id: string, input: string) {
  const spec = await loadAgent(id);
  const res = await fetch(process.env.ARCHITECT_RUNTIME_URL + '/run', {
    method: 'POST',
    headers: { authorization: \`Bearer \${process.env.ARCHITECT_RUNTIME_KEY}\`, 'content-type': 'application/json' },
    body: JSON.stringify({ spec, input }),
  });
  return res.json() as Promise<{ reply: string; steps: unknown[] }>;
}

export async function recentRuns(agentId: string, limit = 5) {
  return [] as { id: string; summary: string; steps: number; at: string }[];
}
`);
  add('app/api/agents/[id]/route.ts', `// POST /api/agents/:id  { input } → { reply }
import { NextResponse } from 'next/server';
import { runAgent } from '@/lib/agents';

const AGENTS = ${JSON.stringify(agents.map((a) => kebab(a.id)))};

export async function POST(req: Request, { params }: { params: { id: string } }) {
  if (!AGENTS.includes(params.id)) return NextResponse.json({ error: 'Unknown agent' }, { status: 404 });
  const { input } = await req.json();
  const out = await runAgent(params.id, String(input ?? ''));
  return NextResponse.json(out);
}
`);
  add('db/schema.sql', schemaSql(project));
  add('db/seed.sql', seedSql(project));
  for (const a of agents) {
    let out = [];
    try { out = agentCode(project, a, 'architect'); } catch (e) { out = [{ path: `agents/${kebab(a.id)}/agent.yaml`, content: `# ${a.name}\n` }]; }
    for (const f of out) add(f.path, f.content);
  }
  add('AGENTS.md', `# Agents in ${project.name}

${agents.map((a) => `## ${a.name} (${a.kind})
${a.role || ''}

- **Model tier:** ${a.model?.tier || 'balanced'}
- **Tools:** ${(a.tools || []).map((t) => `${t.name || t.id} (${(t.actions || []).join(', ')})`).join('; ') || 'none'}
- **Needs approval for:** ${(a.approvals || []).join(', ') || 'nothing'}
- **Guardrails:** ${Object.entries(a.guardrails || {}).filter(([, v]) => v === true).map(([k]) => k).join(', ') || 'none'}
- **Limits:** ${a.limits?.costPerRun ?? '—'} cr/run · ${a.limits?.steps ?? '—'} steps${a.limits?.monthlyBudget ? ` · ${a.limits.monthlyBudget} cr/month` : ''}
`).join('\n') || '_No agents yet._\n'}`);
  add('README.md', `# ${project.name}

${project.description || project.plan?.summary || 'Built with Architect.'}

## Run locally

\`\`\`sh
npm install
cp .env.example .env.local   # fill in the values
npm run db:migrate && npm run db:seed
npm run dev
\`\`\`

## What's inside

- ${screens.length} screens: ${screens.map((s) => `\`${s.route}\``).join(', ')}
- ${tables.length} tables (see \`db/schema.sql\`)
- ${agents.length} agents (see \`AGENTS.md\`)
- ${(project.plan?.promises || []).length} promises, each checked by \`tests/promises.spec.ts\`

Generated by Architect. Edits you make here can be pulled back into Architect.
`);
  add('.env.example', ['# Copy to .env.local — never commit real values', 'DATABASE_URL=postgres://user:password@localhost:5432/app', 'ARCHITECT_RUNTIME_URL=https://runtime.architect.dev', 'ARCHITECT_RUNTIME_KEY=', ...(project.env || []).map((e) => `${e.key}=${e.secret ? '' : (e.values?.draft ?? '')}`)].join('\n') + '\n');
  add('tests/promises.spec.ts', testsSpec(project));

  const ov = project.codeOverrides || {};
  for (const path of Object.keys(ov)) if (!files.some((f) => f.path === path) && ov[path] != null) files.push({ path, content: '', added: true });
  return files.map((f) => {
    const o = ov[f.path];
    const content = o != null ? o : f.content;
    return { path: f.path, lang: langOf(f.path), content, generated: f.content, edited: o != null && o !== f.content };
  });
}

/** Files generated from a checkpoint snapshot (overrides are not part of snapshots). */
export function filesAtCheckpoint(project, cp) {
  if (!cp?.snapshot) return generateFiles({ ...project, codeOverrides: {} });
  return generateFiles({ ...project, ...cp.snapshot, codeOverrides: cp.snapshot.codeOverrides || {} });
}
